openapi: 3.0.3
info:
  title: Unified Translation API
  version: 1.0.0
  description: Simplified Intranet-Web Japanese to English Dictionary and Translation API
  contact:
    name: YasuhiroABE
    url: https://yadiary.net/
    email: yasu@yasundial.org
servers:
- url: http://localhost:8080
paths:
  /.spec:
    get:
      description: providing the openapi schema YAML file.
      responses:
        200:
          description: "200 response"
  /dict: 
    get:
      description: e.g. /dict?q=query-words
      parameters:
      - in: query
        name: q
        required: true
        schema:
          type: string
      responses:
        200:
          description: "200 response"
    post:
      description: e.g. /dict?ja=japanese-words&en=english-words
      parameters:
      - in: query
        name: ja
        required: true
        schema:
          type: string
      - in: query
        name: en
        required: true
        schema:
          type: string
      responses:
        200:
          description: "200 response"
  /trans: 
    get:
      description: e.g. /trnas?q=query-words
      parameters:
      - in: query
        name: q
        required: true
        schema:
          type: string
      responses:
        200:
          description: "200 response"

